'use client'
import Head from 'next/head'
import SectionForTracks from "../components/SectionForTracks";
import {useEffect, useState} from "react";
import Image from "next/image";
import Hero from "../components/Hero";


export default function Home() {



    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className="background ">
                <Hero/>


            </main>
        </>
    )
}
